import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {

  const images = [
    "01",
    "02",
    "03",
  ]

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Rezemapa
        </h1>

        <p className={styles.description}>
         Mapa oficial da Rezende Rammel no Minecraft
        </p>



        <div className={styles.imagesMain}>
          {images.map((imageName, code) => (
            <Image
              className={styles.imageRezende}
              src={`/images/${imageName}.png`}
              alt="Imagem do Rezende"
              width={1280}
              height={720}
              key={code}
            />
          ))}
        </div>


        <div className={styles.download}>
          Baixe agora

          <div className={styles.buttonDownload}>
            Baixe agora
          </div>

        </div>
      </main>

      <footer className={styles.footer}>
      </footer>


    </div>
  )
}
